### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by TonyRenHK** [financialforcedev/ffhttp-googledrive#2]
`ffhttp_GoogleDrive Apex Class  43  28  Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveApps  Apex Class  41  32  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveChanges   Apex Class  41  35  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveChannels  Apex Class  41  36  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveChildren  Apex Class  41  36  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveComments  Apex Class  43  36  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveFiles Apex Class  50  33  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveModelAbout    Apex Class  33  69  Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelAbstractObject   Apex Class  0   0   ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelApiChannel   Apex Class  33  69  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelApp  Apex Class  33  62  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelChange   Apex Class  33  65  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelChannelStop  Apex Class  33  70  Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelChild    Apex Class  33  64  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelComment  Apex Class  33  66  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelError    Apex Class  32  64  Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelFile Apex Class  33  63  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelParent   Apex Class  33  65  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelPermission   Apex Class  33  69  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelPermissionId Apex Class  33  71  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelProperty Apex Class  33  67  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelReply    Apex Class  33  64  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelRevision Apex Class  33  67  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelTest Apex Class  40  73  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbout: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelUser Apex Class  32  63  Dependent class is invalid and needs recompilation: ffhttp_GoogleDriveModelAbstractObject: line 33, column 69: Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveModelWatch    Apex Class  33  65  Invalid type: ffhttp_AbstractJsonSerializable
ffhttp_GoogleDriveParents   Apex Class  41  35  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDrivePermissions   Apex Class  41  39  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveProperties    Apex Class  41  38  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials
ffhttp_GoogleDriveReplies   Apex Class  43  35  Dependent class is invalid and needs recompilation: ffhttp_GoogleDrive: line 43, column 28: Invalid type: ffhttp_Client.Credentials`

**Comment by TonyRenHK** [comment]
Failed : ![2016-09-27 11_13_34-deployment details _ salesforce](https://cloud.githubusercontent.com/assets/9688136/18859071/7667b336-84a3-11e6-9628-41b33a4ba64b.png)

**Comment by mwoodcertinia** [comment]
Hi Tony,

Can you check that you have deployed the Core library (https://github.com/financialforcedev/ffhttp-core), as explained in the configuration section of the Readme file (https://github.com/financialforcedev/ffhttp-googledrive#configuration)? Each of the ffhttp libraries is dependent on this being deployed first.

If you are still having problems then I'm happy to take a further look at this.

Cheers,

Matt

**Comment by TonyRenHK** [comment]
Thank you very much!
