### ISSUE TITLE
Setup steps to create a connector in Salesforce have a mistake

### ISSUE THREAD

**Issue by donmac23** [financialforcedev/ffhttp-googledrive#3]
Step 9 in "Create a Connector for Salesforce" says the following:

> Set the Redirect URI to the same URL as you set in step 12 in the Create an app in Google section.

It should refer to step 13, not 12.

**Comment by afawcett** [comment]
@mattwoodffdc this also looks wrong to me, can you confirm?

**Comment by mwoodcertinia** [comment]
Yes, this was wrong. I've updated the Readme with the correct step.

@donmac23 thanks for spotting this.
